import type { FAQ } from "./calculator-registry";

export const GOLD_VALUE_FAQS: FAQ[] = [
  {
    question: "How much is 1 gram of gold worth today?",
    answer: "The value of 1 gram of gold fluctuates daily based on spot price. As of 2026, gold typically trades around <strong>$60–70 per gram</strong> for pure 24K gold. The actual value depends on current market conditions. Use the calculator above with today's spot price to get an exact figure. <em>Note: Jewelry is often worth less due to purity discounts and dealer markups.</em>",
  },
  {
    question: "What is the difference between 14K and 18K gold?",
    answer: "<strong>18K gold</strong> contains 75% pure gold and <strong>14K gold</strong> contains 58.3% pure gold. This means 18K jewelry is more valuable and more pure, but also softer and more prone to scratching. 14K is more durable and less expensive per item, making it popular for engagement rings and everyday wear. <strong>Formula:</strong> Melt value = weight × spot price × purity factor. A 5-gram 18K ring is worth roughly 30% more in pure gold content than a 5-gram 14K ring of the same weight.",
  },
  {
    question: "What factors affect the price of gold?",
    answer: "Gold prices are influenced by several key factors: <ul><li><strong>Economic uncertainty</strong> — investors flock to gold during recessions</li><li><strong>Interest rates</strong> — lower rates make gold cheaper to hold</li><li><strong>Currency strength</strong> — a weak US dollar boosts gold prices</li><li><strong>Inflation</strong> — gold is a traditional inflation hedge</li><li><strong>Central bank policies</strong> — large purchases or sales move markets</li><li><strong>Supply and mining activity</strong> — limited production supports prices</li></ul>These factors interact daily, creating the price volatility you see in spot markets.",
  },
  {
    question: "How do I sell my gold jewelry for the best price?",
    answer: "To maximize your gold sale value: <strong>1) Get an appraisal</strong> from a certified gemologist to confirm purity (karat stamp). <strong>2) Calculate melt value</strong> using a calculator like the one above — compare it to dealer offers. <strong>3) Shop around</strong> — local coin dealers, pawn shops, and online refiners often pay 5–20% differently. <strong>4) Sell to refiners</strong> for higher spot-price payouts versus retail dealers. <strong>5) Avoid chains</strong> that advertise on TV; they typically offer 30–40% below melt value. <strong>6) Consider timing</strong> — sell when prices spike, not during dips.",
  },
  {
    question: "What does 'spot price' mean for gold?",
    answer: "<strong>Spot price</strong> is the current market rate for one troy ounce of pure gold, updated continuously during trading hours on commodity exchanges like COMEX. <em>Example:</em> if spot price is $2,000/troy oz, then 1 gram of 24K gold = $2,000 ÷ 31.1035 grams/troy oz ≈ $64.30/gram. Your actual sale price will be <strong>less than spot</strong> due to dealer markups, refining fees, and handling costs—typically 85–95% of spot for pure bullion.",
  },
];

export const SILVER_VALUE_FAQS: FAQ[] = [
  {
    question: "What is sterling silver purity and how does it affect value?",
    answer: "<strong>Sterling silver (.925)</strong> contains 92.5% pure silver and is the standard for jewelry and collectibles. <strong>Fine silver (.999)</strong> is purer but softer and rarely used in jewelry. <strong>Coin silver (.900)</strong> was used in US dimes and quarters pre-1965. <strong>Key fact:</strong> tarnish (oxidation) does <strong>not reduce melt value</strong>—your sterling bracelet is worth the same tarnished or polished. The purity percentage directly multiplies your melt value: a 100-gram sterling piece = 100g × 92.5% = 92.5g of actual silver content.",
  },
  {
    question: "How much is a silver coin worth?",
    answer: "Silver coin value has <strong>two components:</strong> <ul><li><strong>Melt value</strong> — based on silver content and current spot price (e.g., a US dime contains ~2.15g of .900 silver)</li><li><strong>Collector/numismatic value</strong> — rare dates, mint marks, or condition can add 10–1000% premium</li></ul>Example: A 1 oz pure silver round with spot price at $30/toz = $30 melt value minimum. A rare 1893-S Morgan Dollar with the same 1 oz of silver might sell for $100+ to collectors. Use the calculator for melt value, then research collector premiums separately.",
  },
  {
    question: "Why is silver industrial demand important?",
    answer: "<strong>Industrial uses account for ~50% of silver demand</strong> globally. Key industries: <ul><li><strong>Electronics</strong> — circuit boards, solar panels, RFID tags</li><li><strong>Photography</strong> — still used in X-ray films and specialized imaging</li><li><strong>Medical</strong> — antimicrobial coatings, wound dressings</li><li><strong>Mirrors and coatings</strong> — reflective surfaces</li></ul>When industrial demand surges (e.g., solar energy expansion), silver prices often outpace gold. When tech slows, silver can drop faster than precious metals tied purely to investment demand. This makes silver more volatile than gold—good for traders, riskier for long-term holders.",
  },
  {
    question: "What does 'tarnish' on silver mean for its value?",
    answer: "<strong>Tarnish is purely cosmetic.</strong> Silver tarnish (black layer) is oxidation—a chemical reaction with sulfur compounds in the air. It has <strong>zero impact on melt value</strong> or purity. A blackened silver bracelet has the same intrinsic worth as a shiny one. However, tarnish <strong>may slightly reduce collector/antique value</strong> if appearance matters to buyers. For selling jewelry, clean tarnish with silver polish (silver oxide doesn't affect the calculation), but the melt value is unchanged whether tarnished or pristine.",
  },
  {
    question: "What are the best ways to sell silver scrap or jewelry?",
    answer: "Selling silver: <strong>1) For melt value:</strong> Local coin/bullion dealers, online refiners (APMEX, JM Bullion)—compare quotes before selling. <strong>2) For collector premium:</strong> Rare coins and antique silver sell better on eBay, specialized numismatic sites, or auctions. <strong>3) Check purity first</strong> — use a magnet test (silver is non-magnetic) or acid test for confidence. <strong>4) Get multiple quotes</strong> — dealer premiums vary 5–15% over spot. <strong>5) Avoid selling to pawn shops</strong> unless urgent; they typically pay 20–30% below market. <strong>6) Timing:</strong> Silver prices fluctuate; selling during market rallies yields more income.",
  },
];

export const COPPER_VALUE_FAQS: FAQ[] = [
  {
    question: "What are copper scrap grades and how do they affect price?",
    answer: "<strong>Copper scrap has multiple grades</strong>, each with different purity and price: <ul><li><strong>#1 Copper (97%)</strong> — pure, bright, bare wire; highest value (~$0.40–0.50/lb)</li><li><strong>#2 Copper (95%)</strong> — light oxidation, mixed wire; mid-tier (~$0.35–0.45/lb)</li><li><strong>Insulated wire (~35%)</strong> — copper wire with plastic coating; lowest value due to processing (~$0.12–0.18/lb)</li><li><strong>Pure (99.9%)</strong> — cathodes, pure bullion; premium pricing</li></ul>Dealers buy based on grade because higher purity requires less processing. A pound of #1 is worth 2–3× more than a pound of insulated wire, even though both contain copper.",
  },
  {
    question: "How is the London Metal Exchange (LME) copper price set?",
    answer: "The <strong>LME (London Metal Exchange)</strong> is the global benchmark for copper pricing. Copper trades in contracts for metric tons (1000 kg) of grade A cathode copper. <strong>Key facts:</strong> <ul><li>Prices update continuously during trading hours (8:00 AM–5:00 PM London time)</li><li>Reflects real-time supply, demand, and inventory data</li><li>Historically, LME prices are ~97–100 USD per pound (varies with grade/purity)</li><li>Your scrap dealer deducts 5–20% from LME as their margin</li></ul>The calculator uses current LME data to estimate scrap value. Industrial buyers lock in LME-linked prices daily.",
  },
  {
    question: "Can I make money recycling copper wire?",
    answer: "<strong>Yes, but margins are small.</strong> Copper recycling economics: <ul><li><strong>Bare wire profit:</strong> Collecting #1 copper wire and selling directly to a scrap yard = ~$0.40/lb, or ~$880 per 1000 lbs (minimal labor)</li><li><strong>Stripping insulation:</strong> Insulated wire (~35% copper value) profits only ~$0.15/lb; stripping labor often eats profits unless you have volume</li><li><strong>Storage and transport:</strong> Copper is heavy; collecting, storing, and hauling to scrap yards is labor-intensive</li><li><strong>Scale matters:</strong> Recyclers process tons weekly; hobbyists collect pounds</li></ul>Best approach: separate wire types, avoid stripping if small quantities, and compare local scrap prices before collecting.",
  },
  {
    question: "What causes copper prices to fluctuate?",
    answer: "Copper is an <strong>economic indicator metal</strong> — its price reflects global manufacturing and construction demand. <strong>Price drivers:</strong> <ul><li><strong>Building/construction cycles</strong> — housing booms increase copper wire demand 10–20%</li><li><strong>Electrical grid expansion</strong> — renewable energy projects boost industrial copper demand</li><li><strong>EV production</strong> — electric vehicles use 3–4× more copper than gas cars; rapid EV growth pushes prices up</li><li><strong>Chinese demand</strong> — China consumes ~50% of global copper; their economic slowdowns tank prices</li><li><strong>Supply shocks</strong> — mine strikes, geopolitical tension (Peru, Chile are top producers) spike prices</li></ul>Copper is more volatile than precious metals but less volatile than oil, making it attractive to commodity traders.",
  },
  {
    question: "How do refiners determine copper scrap purity and value?",
    answer: "Scrap copper is tested by <strong>visual inspection, weight, and assay:</strong> <ul><li><strong>Visual inspection</strong> — experienced buyers sort wire by color (bright = #1, oxidized = #2, insulated = lower grade)</li><li><strong>Magnet test</strong> — pure copper is non-magnetic; magnetic items are discarded or downgraded</li><li><strong>Chemical assay</strong> — refineries use X-ray fluorescence (XRF) or titration for exact purity</li><li><strong>Price-per-pound calculation</strong> — dealers apply the LME price, subtract their margin (8–15%), and pay you a check</li></ul>Large quantities (500+ lbs) may get a better assay than small mixed batches, which might be downgraded 1–2% for sorting/processing labor.",
  },
];

export const PLATINUM_VALUE_FAQS: FAQ[] = [
  {
    question: "Is platinum rarer and more valuable than gold?",
    answer: "<strong>Yes, platinum is rarer and typically more expensive than gold.</strong> <ul><li><strong>Scarcity:</strong> Gold annual production ~3,000 tonnes; platinum ~150–170 tonnes (20× less)</li><li><strong>Price:</strong> Platinum often trades at 1.5–2× the price of gold per troy ounce, though ratios fluctuate (as of 2026, ~$1000–1200/oz vs. gold's ~$2000/oz)</li><li><strong>Mining difficulty:</strong> Platinum ores require extensive refining (extraction from nickel and palladium ores)</li><li><strong>Supply concentration:</strong> 80% comes from South Africa and Russia; geopolitical risk supports prices</li></ul>In jewelry, platinum's rarity, durability (harder than gold), and lustrous white finish make it premium—but it's also 1.5–2× heavier, so a platinum ring weighs more and costs more to craft.",
  },
  {
    question: "Why is platinum used in catalytic converters?",
    answer: "<strong>Platinum is the ideal catalytic converter metal</strong> because: <ul><li><strong>Catalytic efficiency:</strong> Platinum atoms trigger a chemical reaction that converts toxic exhaust (NOx, CO, unburned hydrocarbons) into harmless gases (N2, CO2, H2O) without degrading</li><li><strong>Heat resistance:</strong> Platinum maintains activity at 800–900°C exhaust temperatures without corroding</li><li><strong>Durability:</strong> A single catalytic converter lasts 150,000+ miles if not damaged</li><li><strong>Cost trade-off:</strong> Platinum is expensive, but a 3–5g coating in a converter lasts decades, justifying the expense versus frequent replacement</li></ul>A used catalytic converter with ~1–2g platinum can be worth $300–800 depending on market prices, making theft a problem in some regions.",
  },
  {
    question: "What does the platinum hallmark '950 Pt' mean?",
    answer: "<strong>'950 Pt'</strong> means <strong>95% pure platinum,</strong> the standard for fine platinum jewelry. <strong>Common hallmarks:</strong> <ul><li><strong>950 Pt (95%)</strong> — jewelry standard; excellent durability and purity</li><li><strong>900 Pt (90%)</strong> — slightly lower purity; older jewelry or European standard</li><li><strong>850 Pt (85%)</strong> — rare; more alloys blended in</li><li><strong>Pt or Plat</strong> — sometimes pure platinum, but check for numerical markings</li></ul>Unlike gold (which uses karats 10K–24K), platinum uses percentage hallmarks. A 950 Pt ring at 5 grams = 4.75 grams pure platinum, valued at 95% of melt value. Always check hallmarks before selling; unmarked platinum should be assayed.",
  },
  {
    question: "How do I sell platinum jewelry for the best price?",
    answer: "<strong>Maximize platinum sale value:</strong> <ul><li><strong>1) Confirm purity:</strong> Look for '950 Pt' or similar hallmark. If unmarked, get a professional assay (costs $20–50)</li><li><strong>2) Calculate melt value:</strong> Weight × spot price × purity factor. A 10-gram 950 Pt ring = 10g × 95% × (platinum spot price/31.1035) = estimated melt value</li><li><strong>3) Compare buyers:</strong> Precious metals dealers, online refiners, high-end jewelry buyers—platinum commands higher spreads than gold</li><li><strong>4) Avoid retail jewelry stores</strong> for selling; they pay 40–50% below melt. Use specialized platinum refiners</li><li><strong>5) Batch sales:</strong> Selling multiple platinum items together attracts better wholesale pricing</li></ul>Platinum's rarity and industrial value make it attractive to buyers; expect faster transactions than gold.",
  },
  {
    question: "Why is platinum more durable than gold for jewelry?",
    answer: "<strong>Platinum's durability advantages:</strong> <ul><li><strong>Hardness:</strong> Platinum is harder than 18K gold, resisting scratches and dents better (Mohs scale: Pt ~4.3, gold ~2.5–3)</li><li><strong>Non-allergenic:</strong> Pure platinum is hypoallergenic; no nickel or copper alloying needed for color</li><li><strong>Doesn't fade or tarnish:</strong> Platinum resists oxidation and corrosion, staying white/gray without replating</li><li><strong>Longevity:</strong> A platinum setting can outlast 10 gold settings under the same wear conditions</li><li><strong>Trade-off:</strong> Platinum is 2.15× denser than gold, so a platinum ring weighs nearly twice as much and requires specialized jeweler skills to resize or repair</li></ul>For heirloom-quality jewelry, platinum's durability justifies its higher cost and lower malleability.",
  },
];

export const PALLADIUM_VALUE_FAQS: FAQ[] = [
  {
    question: "How much is palladium worth compared to gold and platinum?",
    answer: "As of 2026, <strong>palladium trades in three tiers:</strong> <ul><li><strong>Platinum:</strong> ~$1000–1200/troy oz (rarest, industrial catalyst demand)</li><li><strong>Gold:</strong> ~$2000/troy oz (investment demand, jewelry standard)</li><li><strong>Palladium:</strong> ~$800–1000/troy oz (volatile, auto catalyst-driven)</li></ul><strong>Key point:</strong> Palladium is cheaper per ounce than gold/platinum, but price swings are dramatic. In 2020, palladium peaked at $2800/oz due to auto demand, then crashed to $1700/oz during the COVID-19 lockdown. Its value is <strong>highly cyclical</strong>—tied to car production and catalytic converter demand, not stable investment demand like gold.",
  },
  {
    question: "Why is palladium used in catalytic converters?",
    answer: "<strong>Palladium is critical for gasoline engine emissions control:</strong> <ul><li><strong>Gasoline cars:</strong> Use palladium (and platinum/rhodium) as catalysts to oxidize CO and unburned hydrocarbons</li><li><strong>Diesel engines:</strong> Use platinum/palladium but in different ratios than gasoline converters</li><li><strong>Cost:</strong> Palladium is cheaper than platinum but still expensive (~1–2g per converter, worth $800–1600/converter)</li><li><strong>Degradation:</strong> Palladium catalysts degrade over time; a 150,000-mile converter may retain only 40–60% activity</li><li><strong>Recycling:</strong> A used catalytic converter with worn palladium is still worth $100–300 for precious metal recovery</li></ul>With global auto production at ~70 million vehicles/year, catalytic converter demand accounts for ~80% of palladium consumption.",
  },
  {
    question: "What causes palladium prices to be so volatile?",
    answer: "<strong>Palladium volatility drivers:</strong> <ul><li><strong>Auto production cycles:</strong> Quarterly earnings reports and production forecasts swing prices 5–10% in one day</li><li><strong>Geopolitical supply shocks:</strong> 40% of palladium comes from Russia; sanctions or mine strikes spike prices instantly</li><li><strong>EV transition:</strong> Electric vehicles don't need catalytic converters, reducing long-term palladium demand; each 1% EV adoption globally = ~0.5–1% demand reduction</li><li><strong>Recycling rates:</strong> Rising scrap catalyst recycling increases supply, pushing prices down</li><li><strong>Investment flows:</strong> Unlike gold (stable investment), palladium has few retail buyers; institutional trades create outsized price swings</li></ul><strong>Lesson:</strong> Palladium is a trader's metal, not a buy-and-hold store of value.",
  },
  {
    question: "Is palladium a good investment?",
    answer: "<strong>Palladium has mixed investment merit:</strong> <ul><li><strong>Pros:</strong> Industrial demand from auto/electronics is real; historically, scarcity has supported long-term appreciation; small, divisible metal for portfolio hedging</li><li><strong>Cons:</strong> Extreme volatility (2–3× swings within 1–2 years); EV adoption erodes future demand; thin retail market (hard to buy/sell in small quantities); no dividend or interest yield like stocks/bonds</li><li><strong>Best use:</strong> Speculation on auto production cycles or short-term trading, <em>not</em> wealth preservation like gold</li><li><strong>Caution:</strong> Palladium reached $2800/oz in 2020, then fell to $1700/oz—investors who bought near peak lost 40% in 2 years</li></ul>Conservative investors should stick to gold or platinum; palladium is for those comfortable with 30–50% price swings.",
  },
  {
    question: "How do I sell palladium jewelry or scrap?",
    answer: "<strong>Selling palladium:</strong> <ul><li><strong>Purity verification:</strong> Look for hallmarks (950, 500, etc.) or request professional assay (~$30–50)</li><li><strong>Market timing:</strong> Palladium price volatility rewards patience—check 3–6 month price trends before selling</li><li><strong>Buyers:</strong> Precious metals refiners, industrial buyers (auto/electronics), online bullion dealers (APMEX, Kitco)</li><li><strong>Pricing:</strong> Expect 5–10% discount to spot price (lower than gold due to market spread)</li><li><strong>Quantity threshold:</strong> Small amounts (<1 oz) may have higher per-gram fees; batching multiple items improves pricing</li><li><strong>Avoid retail jewelry stores</strong> — they pay 30–40% below melt and are unfamiliar with palladium pricing</li></ul>Given palladium's volatility, monitor prices for a few weeks before committing to a sale.",
  },
];

export const RHODIUM_VALUE_FAQS: FAQ[] = [
  {
    question: "How much is rhodium worth and why is it so expensive?",
    answer: "<strong>Rhodium is the rarest and most expensive precious metal:</strong> <ul><li><strong>Price (2026):</strong> ~$5000–7000/troy oz (5–10× more expensive than gold per ounce)</li><li><strong>Scarcity:</strong> Annual production ~100 tonnes globally; 95% comes from South Africa and Russia</li><li><strong>Extreme rarity:</strong> Less rhodium is mined annually than gold is mined in <em>one week</em></li><li><strong>Supply concentration:</strong> Heavy geopolitical risk; Russia-South Africa controls the market</li><li><strong>Industrial dominance:</strong> ~80% used in catalytic converters; supply shocks (mining accidents, sanctions) directly spike prices</li></ul><strong>Cost per item:</strong> A catalytic converter contains only 0.5–1g rhodium, but at $5000/oz, that's $80–160 of rhodium per converter—making recycling valuable.",
  },
    {
    question: "Why is rhodium used in catalytic converters?",
    answer: "<strong>Rhodium excels at reducing nitrogen oxides (NOx):</strong> <ul><li><strong>Three-way catalyst:</strong> Catalytic converters use palladium (oxidize CO/HC) + platinum (oxidize CO) + rhodium (reduce NOx) in combination</li><li><strong>NOx reduction:</strong> Rhodium breaks N-O bonds at high temperatures (800–900°C), converting NOx to harmless N2</li><li><strong>Efficiency:</strong> Rhodium is unmatched for NOx conversion; platinum + palladium alone cannot meet emission standards</li><li><strong>Durability:</strong> Rhodium degrades ~20% per 150,000 miles but remains catalytically active throughout</li><li><strong>Cost-benefit:</strong> A converter with 0.5–1g rhodium (~$3000–6000 value) extends 100,000+ miles of vehicle life, justifying the expense</li></ul>As emission standards tighten globally, rhodium demand remains locked in for the next 10–20 years despite EV growth.",
  },
  {
    question: "Why does rhodium price swing so dramatically?",
    answer: "<strong>Rhodium has the most volatile commodity price on earth:</strong> <ul><li><strong>Thin supply:</strong> Only 100 tonnes/year globally; any disruption (mine shutdown, sanctions, accident) removes 1–5% supply instantly</li><li><strong>Large dealers control pricing:</strong> A handful of refiners (Johnson Matthey, BASF) trade most rhodium; their buying/selling decisions move prices 5–20% daily</li><li><strong>Catalytic converter recycling:</strong> When auto production slows, recycling volumes drop, reducing rhodium scrap supply; this supply shock spikes prices</li><li><strong>Geopolitical risk:</strong> Russia & South Africa supply 95%; sanctions or labor strikes instantly tighten supply</li><li><strong>Historical swings:</strong> Rhodium ranged from $1000/oz (2001) to $10,000/oz (2008) to $5000+/oz (2020–2026)</li></ul><strong>Lesson:</strong> Rhodium is for speculators and industrial buyers, not cautious investors.",
  },
  {
    question: "Can I profit from recovering rhodium from catalytic converters?",
    answer: "<strong>Catalytic converter recycling economics:</strong> <ul><li><strong>Value per converter:</strong> A typical gasoline converter contains ~0.5–1.5g rhodium + palladium + platinum = $800–2000 total precious metal scrap value</li><li><strong>Recycling margin:</strong> Refiners pay 60–80% of metal value (they handle sorting, smelting, assay labor)</li><li><strong>Net profit per converter:</strong> ~$500–1200 after refiner markup</li><li><strong>Scale challenge:</strong> Solo recyclers collect <100 converters/year; commercial recyclers process 10,000+/year and get better pricing</li><li><strong>Legal caution:</strong> Buying used converters is legal; theft is rampant and illegal. Only buy from reputable auto recyclers or shops</li><li><strong>Market dependent:</strong> When rhodium prices spike, profits increase 3–5×; when prices crash, margins shrink</li></ul>Professional auto recyclers run profitable operations; hobbyists find the volume and legal compliance challenging.",
  },
  {
    question: "What is extreme price volatility and how does it affect rhodium buyers?",
    answer: "<strong>Rhodium's price swings affect different buyers differently:</strong> <ul><li><strong>Auto manufacturers:</strong> Lock in prices via long-term supply contracts; sudden spikes increase converter production costs 5–10%, which get passed to consumers</li><li><strong>Recyclers:</strong> Benefit from high prices (sell used converters for more) but hurt by low prices (lower scrap value)</li><li><strong>Investors:</strong> Rhodium ETFs and futures contracts allow betting on price moves, but 30–50% annual swings kill buy-and-hold strategies</li><li><strong>Jewelry makers:</strong> Avoid rhodium for rings/pendants due to cost and volatility; it's used only as a plating on white gold (very thin layer)</li></ul><strong>2008 crash example:</strong> Rhodium spiked to $10,000/oz, then crashed to $2000/oz during the financial crisis—investors who bought peak lost 80% in 18 months.",
  },
];

export const NICKEL_VALUE_FAQS: FAQ[] = [
  {
    question: "How much is nickel worth and why does EV demand matter?",
    answer: "<strong>Nickel pricing and EV demand link:</strong> <ul><li><strong>Price (2026):</strong> ~$7–9/lb or ~$14,000–18,000/metric ton (commodity-based, volatile)</li><li><strong>EV batteries:</strong> Nickel is a key component in lithium-ion battery cathodes; a 100 kWh EV battery contains ~10–30 kg nickel</li><li><strong>Demand surge:</strong> Global EV sales grew 35%/year (2020–2025); with 1.5 million EV sales annually, that's 15,000–45,000 tonnes of nickel/year for batteries alone</li><li><strong>Supply pressure:</strong> Nickel mines can't expand fast enough; Indonesia dominates (40% of supply) but refining capacity lags</li><li><strong>Price forecast:</strong> Nickel is expected to double (2025–2030) due to EV battery demand growth</li></ul><strong>Key takeaway:</strong> Nickel is a proxy for EV industry growth; rising nickel prices = bullish EV outlook.",
  },
  {
    question: "What are the London Metal Exchange (LME) nickel futures?",
    answer: "<strong>LME nickel trading:</strong> <ul><li><strong>Contract unit:</strong> 6 metric tonnes of nickel per futures contract (standard for industrial trading)</li><li><strong>Grade:</strong> High-purity nickel cathodes (99.8%+ purity)</li><li><strong>Price volatility:</strong> Nickel futures swing 10–30% intra-year, making it a popular derivative for traders and producers hedging supply risk</li><li><strong>Your calculator:</strong> Uses spot LME nickel price; your scrap dealer quotes a discount (8–12%) to LME spot</li><li><strong>Trading hours:</strong> LME trading occurs 08:00–17:00 London time, with overnight electronic trading (16:00–08:00)</li></ul>Investors and miners use LME futures to lock in prices months ahead; it's the global benchmark for nickel value.",
  },
  {
    question: "Why were US nickels made of nickel only until 1866?",
    answer: "<strong>US five-cent coin history:</strong> <ul><li><strong>1866–1942:</strong> Nickels were 75% copper + 25% nickel (hence the name, 'nickel')</li><li><strong>1942–1945:</strong> Wartime shortage substituted copper; coins were 56% copper + 35% silver + 9% manganese (no nickel, confusing name!)</li><li><strong>1946–present:</strong> Returned to 75% copper + 25% nickel composition</li><li><strong>Metal value today:</strong> A single nickel coin (~5g) contains ~1.25g nickel (~$0.009) + ~3.75g copper (~$0.015) = ~$0.024 intrinsic metal value vs. face value of $0.05</li><li><strong>Collector note:</strong> 1942–1945 wartime nickels are slightly more collectible due to silver content and historical interest</li></ul>Melting nickels for metal is uneconomical and federally prohibited; they're worth face value in circulation.",
  },
  {
    question: "How is nickel mining affecting the environment?",
    answer: "<strong>Nickel mining environmental concerns:</strong> <ul><li><strong>Laterite ores:</strong> Most nickel comes from laterite deposits in tropical regions (Indonesia, Philippines, New Caledonia); mining requires clearing rainforest</li><li><strong>Acid mine drainage:</strong> Sulfide ore processing creates sulfuric acid; improper containment contaminates rivers and groundwater</li><li><strong>Tailings storage:</strong> Nickel mines generate massive tailings dams; failures have caused environmental disasters (e.g., Brumadinho, Brazil, 2019)</li><li><strong>Energy intensity:</strong> Nickel refining consumes huge electricity; 60% of supply comes from coal-powered Indonesia and Philippines</li><li><strong>Carbon trade-off:</strong> EV batteries need nickel, but mining + refining emit 5–8 tonnes CO2 per tonne nickel</li></ul><strong>Paradox:</strong> Clean EVs require environmentally-intensive nickel mining. Industry is investing in greener extraction and recycling to offset this.",
  },
  {
    question: "What is the relationship between nickel prices and stainless steel?",
    answer: "<strong>Stainless steel is the largest nickel consumer:</strong> <ul><li><strong>Stainless composition:</strong> Stainless steel is 8–12% nickel + 16–26% chromium + iron + other elements</li><li><strong>Demand split:</strong> Stainless steel accounts for ~65% of global nickel consumption; batteries account for ~20%; remaining 15% goes to plating, alloys</li><li><strong>Price correlation:</strong> Nickel and stainless steel prices move together; construction booms increase demand for both</li><li><strong>Chinese production:</strong> China produces 35% of global stainless steel; their construction slowdowns reduce nickel demand 10–20%</li><li><strong>Your scrap:</strong> Stainless steel scrap (bearings, springs, appliance casing) contains 10% nickel; refiners separate and recycle both nickel and iron</li></ul><strong>Macro lesson:</strong> Watch Chinese construction data and stainless steel exports; they predict nickel prices 2–3 months ahead.",
  },
];

export const ALUMINUM_VALUE_FAQS: FAQ[] = [
  {
    question: "How much can I earn recycling aluminum cans?",
    answer: "<strong>Aluminum can recycling economics:</strong> <ul><li><strong>Market price:</strong> Aluminum scrap ~$0.35–0.45/lb (2026), equivalent to ~$0.70–1.40 per can (~24g/can)</li><li><strong>Collection math:</strong> ~26–32 cans = 1 pound; earning $0.35 requires ~30 cans and transport to scrap yard</li><li><strong>Practical volume:</strong> Hand-collecting 100 cans (4 lbs) = ~$1.40–1.80 gross; labor is worth ~$2–3/hour</li><li><strong>Commercial scale:</strong> Bottle deposit states (CA, NY, etc.) pay $0.05–0.10 per can plus scrap value; commercial collectors earn $10–20/hour handling 200+ cans</li><li><strong>Pro tip:</strong> Batch cans until you have 50+ lbs before driving to a scrap yard; fuel costs eat small hauls</li></ul><strong>Bottom line:</strong> Recycling cans is environmental stewardship, not fortune-making for hobbyists.",
  },
  {
    question: "Why does aluminum recycling save 95% of energy versus mining?",
    answer: "<strong>Energy cost comparison:</strong> <ul><li><strong>Mining & refining new aluminum:</strong> Bauxite ore → alumina (calcination, 1200°C) → electrolysis (Hall-Héroult process, 950°C, massive electricity) = ~15–17 kWh per kg aluminum</li><li><strong>Recycling:</strong> Shred scrap → melting (only 650°C) → casting = ~0.5–1 kWh per kg aluminum</li><li><strong>Energy ratio:</strong> Recycling uses 3–7% of primary production energy = <strong>93–97% savings</strong></li><li><strong>Cost impact:</strong> Energy is 30–40% of aluminum production cost; recycling is 40–60% cheaper than mining</li><li><strong>Carbon benefit:</strong> Primary aluminum emits ~12 kg CO2 per kg metal; recycled aluminum emits ~0.5–1 kg CO2/kg = <strong>90% lower carbon footprint</strong></li></ul><strong>This is why aluminum is the most recycled metal (75% recycling rate in some countries).</strong>",
  },
  {
    question: "What is cast aluminum versus sheet aluminum and how does purity matter?",
    answer: "<strong>Aluminum scrap grades:</strong> <ul><li><strong>Cast aluminum (90% purity):</strong> Engine blocks, cylinder heads, transmission cases; harder, brittle; lower scrap value (~$0.32–0.38/lb) due to cost of removing contaminants</li><li><strong>Sheet aluminum (97% purity):</strong> Cans, foil, roofing, siding; clean, soft; higher scrap value (~$0.40–0.45/lb) due to easier recycling</li><li><strong>Pure aluminum (99.7%):</strong> Electrical conductors, aerospace; premium scrap value (~$0.45–0.55/lb)</li><li><strong>Mixed scrap (~80% purity):</strong> Appliances, automotive trim with copper/brass contamination; downgraded value (~$0.25–0.32/lb)</li></ul><strong>Sorting tip:</strong> Separate cans (sheet) from engine parts (cast); dealers pay 20–50% more for clean grades.",
  },
  {
    question: "How much aluminum is in my old smartphone or laptop?",
    answer: "<strong>Aluminum in electronics:</strong> <ul><li><strong>Smartphone:</strong> ~5–10g aluminum (chassis, heat sinks); worth ~$0.02–0.04 in scrap, but device contains ~$1–2 in gold, copper, rare earths (more valuable to recover)</li><li><strong>Laptop:</strong> ~200–300g aluminum (chassis, heatsinks); worth ~$0.07–0.13 in scrap alone, but again, integrated circuits have higher value/oz</li><li><strong>Recycling economics:</strong> E-waste recyclers focus on copper, gold, and rare earth elements first; aluminum is harvested as a by-product after precious metal recovery</li><li><strong>Individual recycling:</strong> Collecting old electronics for aluminum alone is uneconomical; e-waste programs handle the full material recovery</li></ul><strong>Bottom line:</strong> E-waste has more value in gold, copper, and rare earths than aluminum.",
  },
  {
    question: "What factors affect aluminum commodity prices?",
    answer: "<strong>Aluminum price drivers:</strong> <ul><li><strong>Electricity costs:</strong> Smelting is 30–40% electricity; cheap hydropower (Norway, Iceland, Canada) supports low prices; expensive coal power (China) increases prices</li><li><strong>China's production:</strong> China produces 60% of global aluminum; their factory shutdowns (environmental regulations) spike prices</li><li><strong>Construction cycles:</strong> Building booms drive 40% of aluminum demand (windows, frames, roofing); housing slowdowns crater prices</li><li><strong>Transportation/logistics:</strong> Aluminum is energy-dense to ship; oil prices indirectly affect aluminum value</li><li><strong>Recycling rates:</strong> High recycling (in developed nations) increases scrap supply, moderating primary aluminum prices</li></ul><strong>Macro setup:</strong> Watch China construction data and global electricity prices to forecast aluminum 3–6 months ahead.",
  },
];

export const ZINC_VALUE_FAQS: FAQ[] = [
  {
    question: "What is galvanization and why does it matter for zinc value?",
    answer: "<strong>Galvanization is the primary use of zinc:</strong> <ul><li><strong>Process:</strong> Steel is dipped in molten zinc (~840°C); zinc coating (0.5–2mm thick) bonds to steel surface</li><li><strong>Purpose:</strong> Zinc oxidizes before steel, preventing rust (galvanic protection); coating lasts 30–50 years outdoors</li><li><strong>Applications:</strong> ~50% of zinc demand goes to galvanization: roofing, guardrails, electrical poles, automotive bodies, appliances</li><li><strong>Recycling:</strong> Galvanized steel scrap contains 1–2% zinc by weight; refiners separate zinc from steel during processing</li><li><strong>Cost-benefit:</strong> Adding 0.5 kg zinc to 10 kg steel costs ~$1–2 but prevents $50–100 rust damage, making galvanization economically essential</li></ul><strong>Key insight:</strong> Zinc demand is tied to construction and automotive production—rising when economies boom, falling during recessions.",
  },
  {
    question: "How much zinc is in a US penny and what is it worth?",
    answer: "<strong>US penny composition (1982–present):</strong> <ul><li><strong>Core:</strong> 97.5% zinc + 2.5% copper plating (~2.5g per penny)</li><li><strong>History:</strong> Pre-1982 pennies were 95% copper (worth ~$0.016 in copper alone); inflation forced the switch to cheap zinc</li><li><strong>Zinc content:</strong> Each penny contains ~2.4g zinc + 0.1g copper = ~$0.008 intrinsic metal value at 2026 prices</li><li><strong>Historical quirk:</strong> In the late 1970s–early 1980s, copper prices spiked, making pre-1982 pennies worth melting (now federally prohibited)</li><li><strong>Collecting:</strong> Rare date pennies (1943-S Steel, 1969-S, 1995-W) have numismatic value ($5–100+), far exceeding metal value</li></ul><strong>Fun fact:</strong> Melting pennies is illegal; but their metal value is ~$0.008 vs. $0.01 face value—a losing proposition anyway.",
  },
  {
    question: "What is the London Metal Exchange (LME) price for zinc?",
    answer: "<strong>LME zinc trading:</strong> <ul><li><strong>Contract unit:</strong> 25 metric tonnes (high-grade slab zinc, 99.99% purity)</li><li><strong>Price range (2026):</strong> ~$0.90–1.20/lb or ~$1800–2400/metric ton (highly cyclical)</li><li><strong>Trading hours:</strong> 08:00–17:00 London time (08:00 CET / 03:00 EDT) with electronic overnight trading</li><li><strong>Spot vs. futures:</strong> Spot price reflects immediate delivery; futures (3–12 month contracts) allow producers/buyers to hedge price risk</li><li><strong>Your scrap pricing:</strong> Scrap dealers quote 8–15% below LME spot; their margin covers logistics, assay, refining</li></ul><strong>Market volatility:</strong> Zinc prices swung $1.00–1.40/lb (2020–2026) due to Chinese infrastructure demand shifts.",
  },
  {
    question: "How is zinc used in die-casting for automotive parts?",
    answer: "<strong>Zinc die-casting in auto industry:</strong> <ul><li><strong>Process:</strong> Molten zinc (380–420°C) is injected under high pressure into steel dies; parts cool in 2–10 seconds</li><li><strong>Advantages:</strong> <ul><li>Precision—die-cast zinc parts are accurate to ±0.05mm (no secondary machining needed)</li><li>Strength—zinc alloys (with aluminum, copper) match aluminum strength but are cheaper</li><li>Speed—high throughput (1000+ parts/hour) vs. steel forging (10–100/hour)</li><li>Cost—die-casting tooling is cheaper than stamping or forging for small runs</li></ul><li><strong>Applications:</strong> Valve bodies, connectors, carburetor bodies, transmission housings, door locks</li><li><strong>Recyclability:</strong> Zinc die-cast scrap is re-melted at ~$0.85–1.00/lb, recovering ~90% of input zinc</li></ul><strong>Market impact:</strong> Automotive production slowdowns reduce die-casting zinc demand 10–15%, visible in monthly LME price data.",
  },
  {
    question: "Why is zinc essential for the EV battery supply chain?",
    answer: "<strong>Zinc's growing EV role:</strong> <ul><li><strong>Galvanization dominance:</strong> Even as lithium-ion batteries dominate power storage, EV manufacturing still requires extensive galvanized steel (chassis, structural beams, fasteners)—zinc indispensable</li><li><strong>Zinc-based alternatives:</strong> Researchers are exploring zinc-air and zinc-ion batteries as cheaper alternatives to lithium-ion for stationary storage (power grids)</li><li><strong>Demand shift:</strong> EV production growing 35%/year; each EV uses 2–3× more galvanized components than ICE cars (aluminum body = less steel, but still zinc-coated fasteners)</li><li><strong>Long-term outlook:</strong> Zinc demand is expected to grow 2–3% annually through 2035, driven by EVs + renewable energy infrastructure (galvanized transmission towers)</li></ul><strong>Investment takeaway:</strong> Zinc is a stable, slow-growth industrial metal—less exciting than nickel (battery-focused) but fundamentally sound.",
  },
];

export const LEAD_VALUE_FAQS: FAQ[] = [
  {
    question: "How much lead value is in a used car battery and why?",
    answer: "<strong>Lead-acid battery composition and value:</strong> <ul><li><strong>Weight breakdown:</strong> A typical 12V car battery (~30 kg) contains ~13 kg lead + 6 kg lead dioxide + ~3 kg sulfuric acid + 8 kg plastic/other</li><li><strong>Lead value (2026):</strong> At ~$0.45/lb lead, a battery's lead scrap is worth ~$13 (13 kg = 28.7 lbs × $0.45 = ~$12.90)</li><li><strong>Lead dioxide value:</strong> Worth slightly more per unit than pure lead; recyclers separate it</li><li><strong>Recycling economics:</strong> A battery costs $15–30 to buy; its $12–15 scrap lead value makes battery recycling a viable $0.50–5 proposition if bundled with other scrap or done at scale</li><li><strong>Why batteries matter:</strong> 98% of lead-acid batteries are recycled globally; lead recycling is one of the most efficient material cycles on earth</li></ul><strong>Key insight:</strong> Dead batteries are valuable scrap—always recycle, never throw away.",
  },
  {
    question: "What are the health and safety concerns when handling lead?",
    answer: "<strong>Lead toxicity and safety:</strong> <ul><li><strong>Exposure risks:</strong> <ul><li>Inhalation — lead dust/fumes from melting, cutting, or grinding battery plates</li><li>Ingestion — lead particles on hands entering mouth (especially dangerous for children)</li><li>Absorption — lead oxide powder absorbs through skin during prolonged contact</li></ul><li><strong>Health effects:</strong> Chronic exposure → neurological damage (reduced IQ, learning disabilities in children), kidney damage, anemia, reproductive harm</li><li><strong>Safe handling:</strong> <ul><li>Wear gloves, respirator (P100 filter), and eye protection when disassembling batteries</li><li>Wash hands thoroughly before eating/drinking</li><li>Work in ventilated areas; never smoke or eat near lead</li><li>Dispose of lead through certified recyclers, not household trash</li></ul><li><strong>Regulations:</strong> OSHA enforces lead exposure limits (~0.05 mg/m³); recycling facilities have strict protocols</li></ul><strong>Bottom line:</strong> Lead is valuable but requires respect; professional recyclers have proper equipment and training.",
  },
  {
    question: "What is the London Metal Exchange (LME) lead price and how does it affect scrap value?",
    answer: "<strong>LME lead trading:</strong> <ul><li><strong>Contract:</strong> 25 metric tonnes of 99.97% pure lead</li><li><strong>Price (2026):</strong> ~$0.40–0.50/lb or ~$800–1000/metric ton</li><li><strong>Trading hours:</strong> 08:00–17:00 London time (08:00 CET / 03:00 EDT) with overnight electronic trading</li><li><strong>Historical context:</strong> Lead prices are tied to automotive (batteries) and construction (roofing, radiation shielding); they swing 20–40% annually based on economic outlook</li><li><strong>Scrap premium:</strong> Clean lead scrap (95%+ pure) trades 5–10% below LME; contaminated scrap (80–85% purity) trades 15–20% below</li></ul><strong>Your battery scrap:</strong> A 30-kg battery with ~13 kg lead scrap = value ~$6–8 after refiner processing and purity adjustments.",
  },
  {
    question: "How is recycled lead used and why is lead recycling so efficient?",
    answer: "<strong>Lead recycling advantages:</strong> <ul><li><strong>Secondary lead supply:</strong> Recycled lead accounts for ~70% of global lead supply (vs. mining ~30%); this is the highest recycling rate of any major metal</li><li><strong>Quality parity:</strong> Recycled lead is chemically identical to primary lead; both are 99.97%+ pure after refining</li><li><strong>Energy efficiency:</strong> Recycling requires ~20% of the energy of mining + smelting primary lead ore</li><li><strong>End uses:</strong> <ul><li>~80% → new car/backup batteries (closed loop: old battery → melted → new battery)</li><li>~10% → radiation shielding (medical, nuclear facilities, X-ray rooms)</li><li>~5% → ammunition, wheel weights, cable sheathing</li><li>~5% → solder, pigments (declining due to toxicity regulations)</li></ul><li><strong>Economic driver:</strong> Lead's industrial value (not rare, not precious) makes recycling economically self-sustaining without subsidies</li></ul><strong>Environmental win:</strong> Lead recycling keeps hazardous material out of landfills and reduces mining's ecological footprint.",
  },
  {
    question: "What is the long-term outlook for lead demand and prices?",
    answer: "<strong>Lead demand trends (2026–2035):</strong> <ul><li><strong>Automotive stability:</strong> Battery demand grows 2–3% annually (new EVs don't need 12V lead-acid for propulsion, but all EVs need 12V auxiliary systems). Lead-acid demand is flat to slightly declining</li><li><strong>Grid storage opportunity:</strong> Lead-acid batteries are cheap ($100–150/kWh) vs. lithium ($300–500/kWh); they're being deployed for residential backup and microgrid storage, offsetting vehicle demand loss</li><li><strong>Price forecast:</strong> Lead prices are expected to remain in $0.40–0.60/lb range (2026–2030), reflecting stable industrial demand</li><li><strong>Supply security:</strong> Lead is not critical/rare; China and India have ample reserves; no supply crisis expected</li><li><strong>Regulatory headwinds:</strong> Phase-out of lead ammunition (California, some EU nations) and lead-based paint accelerates, but battery recycling dominates demand (95%+)</li></ul><strong>Investment angle:</strong> Lead is a stable, slow-growth commodity—best viewed as portfolio ballast, not appreciation play.",
  },
];

export const TIN_VALUE_FAQS: FAQ[] = [
  {
    question: "What is solder and why is tin solder valuable?",
    answer: "<strong>Tin solder fundamentals:</strong> <ul><li><strong>Solder composition:</strong> Traditional solder is 60% tin + 40% lead (melting point ~188°C); lead-free solder is 96–99% tin + other metals (higher melting point ~217°C)</li><li><strong>Purpose:</strong> Solder melts to form liquid metal bridges that bond electronic components to circuit boards; it's the glue holding every smartphone, computer, and appliance together</li><li><strong>Tin requirement:</strong> ~40–50% of global tin demand is for electronics solder (declining as miniaturization reduces solder per device)</li><li><strong>Scrap value:</strong> Solder scrap (~60% tin) is worth ~$0.30–0.35/lb (vs. pure tin ~$0.50–0.70/lb)</li><li><strong>E-waste recovery:</strong> Circuit boards are smelted to recover copper, gold, and tin; tin is a significant by-product</li></ul><strong>Key trend:</strong> As devices shrink and adopt lead-free solder (99%+ tin), tin recovery efficiency improves.",
  },
  {
    question: "What is tin plating and where is it used industrially?",
    answer: "<strong>Tin plating applications:</strong> <ul><li><strong>Food cans ('tin cans'):</strong> Steel cans are coated with 0.5–1.5μm tin to prevent rust and food contamination; ~50,000 tonnes tin/year (30% of industrial demand)</li><li><strong>Electronics terminals:</strong> Copper pins/leads are tin-plated to prevent oxidation and improve solderability</li><li><strong>Corrosion protection:</strong> Tin plate thickness: 0.5–2μm; at 1μm, one pound tin can coat ~50,000 square feet</li><li><strong>Cost-benefit:</strong> Tin plate (~$1–2/can) prevents $50–100 food waste losses due to rust/contamination</li><li><strong>Recycling:</strong> Tin-plated cans are recycled; tin is separated during smelting (recovered as secondary tin)</li></ul><strong>Market insight:</strong> Tin demand is 30% food cans, 40% electronics, 30% other; flat demand unless food/electronics production rises.",
  },
  {
    question: "Why is tin supply constrained and which countries are major producers?",
    answer: "<strong>Tin supply constraints:</strong> <ul><li><strong>Production (2026):</strong> ~380,000 tonnes/year globally (stable, not growing)</li><li><strong>Top 3 producers:</strong> <ul><li><strong>Indonesia:</strong> ~40% of global supply (major deposits, but facing environmental regulations slowing expansion)</li><li><strong>China:</strong> ~15% of supply (large internal consumption, limited exports)</li><li><strong>Peru:</strong> ~10% of supply (geopolitically stable production)</li></ul><li><strong>Supply risk:</strong> If Indonesia reduces output (labor strikes, environmental closure), global tin supply tightens 5–15%, spiking prices</li><li><strong>Reserve depletion:</strong> At current extraction rates (~380k tonnes/year), known reserves last ~35–40 years; exploration for new deposits is ongoing</li><li><strong>Price volatility:</strong> Tin swings $0.30–0.80/lb over 3–5 year cycles based on supply shocks</li></ul><strong>Market dynamic:</strong> Tin is a tight market with limited elasticity—supply shocks hit prices hard.",
  },
  {
    question: "How much tin is in an old electronic device and what is it worth?",
    answer: "<strong>Tin content in electronics:</strong> <ul><li><strong>Smartphone:</strong> ~2–5g tin (solder on circuit boards); worth ~$0.04–0.10 at scrap prices</li><li><strong>Laptop:</strong> ~10–20g tin (solder, tin-plated connectors); worth ~$0.10–0.20</li><li><strong>Desktop computer:</strong> ~20–40g tin (more solder than laptops); worth ~$0.20–0.40</li><li><strong>Microwave oven:</strong> ~50–100g tin (transformer, circuit boards, connectors); worth ~$0.30–0.50</li><li><strong>Recycling chain:</strong> E-waste processors shred devices, separate metals magnetically/chemically; tin is recovered as a minor by-product alongside copper, gold, rare earths (which are more valuable per ounce)</li></ul><strong>Economics:</strong> Individual devices aren't recycled for tin alone; tin value is captured as part of bulk e-waste metal recovery.",
  },
  {
    question: "What are supply chain risks for tin and how do they affect prices?",
    answer: "<strong>Tin supply chain vulnerabilities:</strong> <ul><li><strong>Geographic concentration:</strong> Indonesia + China + Peru = 65% of global supply; any major disruption (political instability, environmental regulation, labor strike) tightens supply 10–20%</li><li><strong>Conflict minerals legacy:</strong> Tin from Democratic Republic of Congo (artisanal mining) is labeled 'conflict tin' due to human rights concerns; importers face compliance costs and supply uncertainty</li><li><strong>Mining expansion lag:</strong> Tin exploration and new mine development take 5–10 years; supply can't respond quickly to demand spikes</li><li><strong>Industrial concentration:</strong> ~70% of tin is smelted/refined in Indonesia and China; refinery strikes or environmental closures squeeze supply</li><li><strong>Price forecasts:</strong> Tin is expected to remain tight; prices predicted to average $0.50–0.70/lb through 2030</li></ul><strong>Investor angle:</strong> Tin is underappreciated as a supply-constrained critical metal; geopolitical events can spike prices 20–30% in weeks.",
  },
];
